version: '2'
services:
  app:
    build: ./app
    expose:
      - "80"
    privileged: true
  socat:
    build: ./socat
    network_mode: host
    expose:
      - "8181"
      - "9191"
      - "21000"
    command: socat -v tcp-l:8181,fork exec:"/bin/cat"
  consul:
    image: consul:1.9.1
    #build: ./consul
    network_mode: host
    expose:
      - "8301"
      - "8302"
      - "8500"
      - "8600"
    restart: always
  envoy:
    image: envoyproxy/envoy:v1.16.2
    network_mode: host
    expose:
      - "10000"
  nomad:
    build: ./nomad
    network_mode: host
    expose:
      - "4646"
      - "4647"
      - "4648"
    labels:
      io.balena.features.balena-socket: '1'
    privileged: true
    restart: always
