version: '2'
services:
  app:
    build: ./app
    expose:
      - "80"
    privileged: true
  consul:
    #image: consul:1.9.1
    build: ./consul
    network_mode: host
    expose:
      - "8301"
      - "8302"
      - "8500"
      - "8600"
    restart: always
  nomad:
    build: ./nomad
    network_mode: host
    expose:
      - "4646"
      - "4647"
      - "4648"
    labels:
      io.balena.features.balena-socket: '1'
    privileged: true
    restart: always
