# Most probably this should used: 'raspberrypi4-64'
FROM balenalib/%%BALENA_MACHINE_NAME%%-alpine:edge-build

RUN apk --update-cache add cmake python3 python3-dev py3-pip && rm -rf /var/cache/apk/*
RUN python3 --version

COPY ["rtimul", "/opt/lib"]
WORKDIR /opt/lib
RUN cmake RTIMULib
RUN make
RUN make install

WORKDIR /opt/lib/Linux/python
RUN python3 setup.py build
RUN python3 setup.py install

RUN python3 -m pip install sense-hat

COPY demo.py /opt/app.py
CMD ["python3", "/opt/app.py"]
